name: Publish thewagner.net

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/checkout@v1
      with:
        repository: getpelican/pelican-themes.git
        submodules: true
        path: thewagner.net/themes
        ref: 68178af

    - uses: actions/checkout@v1
      with:
        repository: getpelican/pelican-plugins.git
        submodules: true
        path: thewagner.net/plugins
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to GitHub pages
      run: |
        make github
