name: Publish thewagner.net

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install

#    - name: Deploy to GitHub pages
#      run: |
#        pipenv run make github
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
