---
name: "Build and deploy site"
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build -A checks.x86_64-linux
      - run: |
          scripts/publish.sh
          scripts/push_image.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        if: github.ref == 'refs/heads/master'
